// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGE.Backend.Data;

#nullable disable

namespace SGE.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SGE.Backend.Models.AccesorioEquipo", b =>
                {
                    b.Property<int>("IdAccesorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_accesorio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAccesorio"));

                    b.Property<string>("DescripcionAccesorio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("descripcion_accesorio");

                    b.Property<string>("FotoAccesoriosUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("foto_accesorios_url");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("int")
                        .HasColumnName("id_equipo");

                    b.HasKey("IdAccesorio");

                    b.HasIndex("IdEquipo");

                    b.ToTable("accesorios_equipo");
                });

            modelBuilder.Entity("SGE.Backend.Models.Carrera", b =>
                {
                    b.Property<int>("IdCarrera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_carrera");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarrera"));

                    b.Property<int>("IdFacultad")
                        .HasColumnType("int")
                        .HasColumnName("id_facultad");

                    b.Property<string>("NombreCarrera")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_carrera");

                    b.HasKey("IdCarrera");

                    b.HasIndex("IdFacultad");

                    b.ToTable("carreras");
                });

            modelBuilder.Entity("SGE.Backend.Models.Equipo", b =>
                {
                    b.Property<int>("IdEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_equipo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEquipo"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<string>("FotoEquipoUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("foto_equipo_url");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int")
                        .HasColumnName("id_estudiante");

                    b.Property<int>("IdMarca")
                        .HasColumnType("int")
                        .HasColumnName("id_marca");

                    b.Property<int>("IdTipo")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("serial");

                    b.HasKey("IdEquipo");

                    b.HasIndex("IdEstudiante");

                    b.HasIndex("IdMarca");

                    b.HasIndex("IdTipo");

                    b.HasIndex("Serial")
                        .IsUnique();

                    b.ToTable("equipos");
                });

            modelBuilder.Entity("SGE.Backend.Models.Estudiante", b =>
                {
                    b.Property<int>("IdEstudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estudiante");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstudiante"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("apellidos");

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("correo_electronico");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<string>("FotoPerfilUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("foto_perfil_url");

                    b.Property<int>("IdCarrera")
                        .HasColumnType("int")
                        .HasColumnName("id_carrera");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombres");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("numero_documento");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdEstudiante");

                    b.HasIndex("CorreoElectronico")
                        .IsUnique()
                        .HasFilter("[correo_electronico] IS NOT NULL");

                    b.HasIndex("IdCarrera");

                    b.HasIndex("NumeroDocumento")
                        .IsUnique();

                    b.ToTable("estudiantes");
                });

            modelBuilder.Entity("SGE.Backend.Models.Facultad", b =>
                {
                    b.Property<int>("IdFacultad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_facultad");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFacultad"));

                    b.Property<string>("NombreFacultad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_facultad");

                    b.HasKey("IdFacultad");

                    b.HasIndex("NombreFacultad")
                        .IsUnique();

                    b.ToTable("facultades");
                });

            modelBuilder.Entity("SGE.Backend.Models.LogAuditoria", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_log");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLog"));

                    b.Property<string>("AccionRealizada")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("accion_realizada");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_hora");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdLog");

                    b.HasIndex("IdUsuario");

                    b.ToTable("log_auditoria");
                });

            modelBuilder.Entity("SGE.Backend.Models.MarcaEquipo", b =>
                {
                    b.Property<int>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_marca");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMarca"));

                    b.Property<string>("NombreMarca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_marca");

                    b.HasKey("IdMarca");

                    b.HasIndex("NombreMarca")
                        .IsUnique();

                    b.ToTable("marcas_equipos");
                });

            modelBuilder.Entity("SGE.Backend.Models.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_permiso");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<string>("NombrePermiso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_permiso");

                    b.HasKey("IdPermiso");

                    b.HasIndex("NombrePermiso")
                        .IsUnique();

                    b.ToTable("permisos");
                });

            modelBuilder.Entity("SGE.Backend.Models.Porteria", b =>
                {
                    b.Property<int>("IdPorteria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_porteria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPorteria"));

                    b.Property<int>("IdSede")
                        .HasColumnType("int")
                        .HasColumnName("id_sede");

                    b.Property<string>("NombrePorteria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_porteria");

                    b.HasKey("IdPorteria");

                    b.HasIndex("IdSede");

                    b.ToTable("porterias");
                });

            modelBuilder.Entity("SGE.Backend.Models.RegistroAcceso", b =>
                {
                    b.Property<int>("IdRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_registro");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRegistro"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_hora");

                    b.Property<int?>("IdEquipo")
                        .HasColumnType("int")
                        .HasColumnName("id_equipo");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int")
                        .HasColumnName("id_estudiante");

                    b.Property<int>("IdPorteria")
                        .HasColumnType("int")
                        .HasColumnName("id_porteria");

                    b.Property<int>("IdUsuarioGuardia")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_guardia");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tipo_movimiento");

                    b.HasKey("IdRegistro");

                    b.HasIndex("IdEquipo");

                    b.HasIndex("IdEstudiante");

                    b.HasIndex("IdPorteria");

                    b.HasIndex("IdUsuarioGuardia");

                    b.ToTable("registro_accesos");
                });

            modelBuilder.Entity("SGE.Backend.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("nombre_rol");

                    b.HasKey("IdRol");

                    b.HasIndex("NombreRol")
                        .IsUnique();

                    b.ToTable("roles");
                });

            modelBuilder.Entity("SGE.Backend.Models.RolPermiso", b =>
                {
                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("int")
                        .HasColumnName("id_permiso");

                    b.HasKey("IdRol", "IdPermiso");

                    b.HasIndex("IdPermiso");

                    b.ToTable("roles_permisos");
                });

            modelBuilder.Entity("SGE.Backend.Models.Sede", b =>
                {
                    b.Property<int>("IdSede")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_sede");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSede"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("direccion");

                    b.Property<string>("NombreSede")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_sede");

                    b.HasKey("IdSede");

                    b.ToTable("sedes");
                });

            modelBuilder.Entity("SGE.Backend.Models.TipoEquipo", b =>
                {
                    b.Property<int>("IdTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipo"));

                    b.Property<string>("NombreTipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_tipo");

                    b.HasKey("IdTipo");

                    b.HasIndex("NombreTipo")
                        .IsUnique();

                    b.ToTable("tipos_equipos");
                });

            modelBuilder.Entity("SGE.Backend.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("usuario");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("SGE.Backend.Models.AccesorioEquipo", b =>
                {
                    b.HasOne("SGE.Backend.Models.Equipo", "Equipo")
                        .WithMany("Accesorios")
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("SGE.Backend.Models.Carrera", b =>
                {
                    b.HasOne("SGE.Backend.Models.Facultad", "Facultad")
                        .WithMany("Carreras")
                        .HasForeignKey("IdFacultad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facultad");
                });

            modelBuilder.Entity("SGE.Backend.Models.Equipo", b =>
                {
                    b.HasOne("SGE.Backend.Models.Estudiante", "Estudiante")
                        .WithMany("Equipos")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGE.Backend.Models.MarcaEquipo", "Marca")
                        .WithMany("Equipos")
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGE.Backend.Models.TipoEquipo", "Tipo")
                        .WithMany("Equipos")
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Marca");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("SGE.Backend.Models.Estudiante", b =>
                {
                    b.HasOne("SGE.Backend.Models.Carrera", "Carrera")
                        .WithMany("Estudiantes")
                        .HasForeignKey("IdCarrera")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("SGE.Backend.Models.LogAuditoria", b =>
                {
                    b.HasOne("SGE.Backend.Models.Usuario", "Usuario")
                        .WithMany("LogsAuditoria")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGE.Backend.Models.Porteria", b =>
                {
                    b.HasOne("SGE.Backend.Models.Sede", "Sede")
                        .WithMany("Porterias")
                        .HasForeignKey("IdSede")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("SGE.Backend.Models.RegistroAcceso", b =>
                {
                    b.HasOne("SGE.Backend.Models.Equipo", "Equipo")
                        .WithMany("RegistrosAccesos")
                        .HasForeignKey("IdEquipo");

                    b.HasOne("SGE.Backend.Models.Estudiante", "Estudiante")
                        .WithMany("RegistrosAccesos")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGE.Backend.Models.Porteria", "Porteria")
                        .WithMany("RegistrosAccesos")
                        .HasForeignKey("IdPorteria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGE.Backend.Models.Usuario", "Guardia")
                        .WithMany("RegistrosAccesosGuardia")
                        .HasForeignKey("IdUsuarioGuardia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Estudiante");

                    b.Navigation("Guardia");

                    b.Navigation("Porteria");
                });

            modelBuilder.Entity("SGE.Backend.Models.RolPermiso", b =>
                {
                    b.HasOne("SGE.Backend.Models.Permiso", "Permiso")
                        .WithMany("RolesPermisos")
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGE.Backend.Models.Rol", "Rol")
                        .WithMany("RolesPermisos")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SGE.Backend.Models.Usuario", b =>
                {
                    b.HasOne("SGE.Backend.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SGE.Backend.Models.Carrera", b =>
                {
                    b.Navigation("Estudiantes");
                });

            modelBuilder.Entity("SGE.Backend.Models.Equipo", b =>
                {
                    b.Navigation("Accesorios");

                    b.Navigation("RegistrosAccesos");
                });

            modelBuilder.Entity("SGE.Backend.Models.Estudiante", b =>
                {
                    b.Navigation("Equipos");

                    b.Navigation("RegistrosAccesos");
                });

            modelBuilder.Entity("SGE.Backend.Models.Facultad", b =>
                {
                    b.Navigation("Carreras");
                });

            modelBuilder.Entity("SGE.Backend.Models.MarcaEquipo", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("SGE.Backend.Models.Permiso", b =>
                {
                    b.Navigation("RolesPermisos");
                });

            modelBuilder.Entity("SGE.Backend.Models.Porteria", b =>
                {
                    b.Navigation("RegistrosAccesos");
                });

            modelBuilder.Entity("SGE.Backend.Models.Rol", b =>
                {
                    b.Navigation("RolesPermisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SGE.Backend.Models.Sede", b =>
                {
                    b.Navigation("Porterias");
                });

            modelBuilder.Entity("SGE.Backend.Models.TipoEquipo", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("SGE.Backend.Models.Usuario", b =>
                {
                    b.Navigation("LogsAuditoria");

                    b.Navigation("RegistrosAccesosGuardia");
                });
#pragma warning restore 612, 618
        }
    }
}
